Config = {}

Config.DiscordWebHook = ''

Config.EmoteResource = 'native' -- native, this is where you set you animation resource ONLY SUPPORTS NATIVE ATM

Config.Notify = 'ox' -- Notify method ox for ox_lib TODO ADD MORE

Config.EnableMenu = true -- Enables PD action menu REQUIRES OX_LIB

Config.EnableRadial = true -- Enables Premade radials REQUIRES OX_LIB

Config.PDJobs = { -- The jobs that have access to PD functions
    'police',
}

Config.EnableTackle = true -- Enables the Tackle keybind

Config.Tacklekeybind = 'H'

Config.EnableCuffKeys = true -- Enables Handcuff keybinds

Config.SoftCuffKey = '->'

Config.HardCuffKey = '<-'

Config.Guns = { -- Where you set the items detected by frisk only supports weapons atm.
    "WEAPON_PISTOL_MK2",
    "WEAPON_ASSAULTSMG",
    "WEAPON_MOLOTOV",
    "WEAPON_SMG_MK2",
    "WEAPON_POOLCUE",
    "WEAPON_GRENADE",
    "WEAPON_MARKSMANPISTOL",
    "WEAPON_BULLPUPSHOTGUN",
    "WEAPON_BOTTLE",
    "WEAPON_COMBATMG",
    "WEAPON_MINISMG",
    "WEAPON_SWEEPERSHOTGUN",
    "WEAPON_ASSAULTRIFLE_MK2",
    "WEAPON_CARBINERIFLE_MK2",
    "WEAPON_BAT",
    "WEAPON_HEAVYSNIPER_MK2",
    "WEAPON_PUMPSHOTGUN_MK2",
    "WEAPON_FLASHLIGHT",
    "WEAPON_COMBATPDW",
    "WEAPON_COMBATPISTOL",
    "WEAPON_SNSPISTOL_MK2",
    "WEAPON_FIREWORK",
    "WEAPON_COMPACTRIFLE",
    "WEAPON_MACHINEPISTOL",
    "WEAPON_MARKSMANRIFLE",
    "WEAPON_AUTOSHOTGUN",
    "WEAPON_PROXMINE",
    "WEAPON_REVOLVER",
    "WEAPON_COMBATSHOTGUN",
    "WEAPON_MILITARYRIFLE",
    "WEAPON_RAYCARBINE",
    "WEAPON_BULLPUPRIFLE",
    "WEAPON_GUSENBERG",
    "WEAPON_HEAVYSHOTGUN",
    "WEAPON_FLARE",
    "WEAPON_KNIFE",
    "WEAPON_STONE_HATCHET",
    "WEAPON_GRENADELAUNCHER_SMOKE",
    "WEAPON_CERAMICPISTOL",
    "WEAPON_ASSAULTRIFLE",
    "WEAPON_PIPEBOMB",
    "WEAPON_MICROSMG",
    "WEAPON_DAGGER",
    "WEAPON_MUSKET",
    "WEAPON_RAYMINIGUN",
    "WEAPON_SPECIALCARBINE",
    "WEAPON_GADGETPISTOL",
    "WEAPON_APPISTOL",
    "WEAPON_ASSAULTSHOTGUN",
    "WEAPON_HEAVYPISTOL",
    "WEAPON_HOMINGLAUNCHER",
    "WEAPON_PIPEWRENCH",
    "WEAPON_MARKSMANRIFLE_MK2",
    "WEAPON_RAYPISTOL",
    "WEAPON_FIREEXTINGUISHER",
    "WEAPON_MINIGUN",
    "WEAPON_PETROLCAN",
    "WEAPON_HATCHET",
    "WEAPON_DBSHOTGUN",
    "WEAPON_DOUBLEACTION",
    "WEAPON_REVOLVER_MK2",
    "WEAPON_COMPACTLAUNCHER",
    "WEAPON_STUNGUN",
    "WEAPON_BULLPUPRIFLE_MK2",
    "WEAPON_SWITCHBLADE",
    "WEAPON_SNIPERRIFLE",
    "WEAPON_KNUCKLE",
    "WEAPON_SPECIALCARBINE_MK2",
    "WEAPON_NIGHTSTICK",
    "WEAPON_SAWNOFFSHOTGUN",
    "WEAPON_CROWBAR",
    "WEAPON_RPG",
    "WEAPON_GRENADELAUNCHER",
    "WEAPON_HEAVYSNIPER",
    "WEAPON_RAILGUN",
    "WEAPON_PISTOL50",
    "WEAPON_SMG",
    "WEAPON_HAMMER",
    "WEAPON_PISTOL",
    "WEAPON_GOLFCLUB",
    "WEAPON_SNSPISTOL",
    "WEAPON_CARBINERIFLE",
    "WEAPON_PUMPSHOTGUN",
    "WEAPON_HAZARDCAN",
    "WEAPON_DIGISCANNER",
    "WEAPON_NAVYREVOLVER",
    "WEAPON_SMOKEGRENADE",
    "WEAPON_BZGAS",
    "WEAPON_ADVANCEDRIFLE",
    "WEAPON_MACHETE",
    "WEAPON_STICKYBOMB",
    "WEAPON_COMBATMG_MK2",
    "WEAPON_VINTAGEPISTOL",
    "WEAPON_MG",
    "WEAPON_FLAREGUN",
}